#!/usr/bin/env bash
# Remnawave PANEL deploy script — Nginx + nftables edition
# by qellyka
#
# Installs only the panel (+ subscription page). For nodes, use
# remnawave-node-deploy.sh from the same repo — it's a separate file so each
# script stays focused on one job and doesn't drag in the other's helpers.
#
# NOTE on the write_*_script() functions below: these embed small Python
# helper scripts as heredocs and write themselves to disk at runtime — you
# never need to upload or manage those .py files separately.
set -euo pipefail

trap 'echo -e "\033[1;31m[ERROR]\033[0m Error at line $LINENO"; exit 1' ERR
log()  { echo -e "\033[1;32m[INFO]\033[0m $1"; }
warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }
die()  { echo -e "\033[1;31m[ERROR]\033[0m $1"; exit 1; }

read_domain() {
  local prompt="$1" __resultvar="$2" value
  while true; do
    read -rp "$prompt" value
    value=$(printf '%s' "$value" | tr -cd 'a-zA-Z0-9.-')
    if [[ "$value" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$ ]]; then
      printf -v "$__resultvar" '%s' "$value"
      return 0
    fi
    warn "Похоже на некорректный домен — возможно, при вводе/вставке приклеился"
    warn "случайный символ (например от переключения раскладки). Введи ещё раз."
  done
}

banner() {
  clear
  echo "==================================================="
  echo "    ____  ________  ____   _____ _       _____ _    ________"
  echo "   / __ \\/ ____/  |/  / | / /   | |     / /   | |  / / ____/"
  echo "  / /_/ / __/ / /|_/ /  |/ / /| | | /| / / /| | | / / __/   "
  echo " / _, _/ /___/ /  / / /|  / ___ | |/ |/ / ___ | |/ / /___   "
  echo "/_/ |_/_____/_/  /_/_/ |_/_/  |_|__/|__/_/  |_|___/_____/   "
  echo ""
  echo "        DEPLOY SCRIPT (Nginx + nftables) — by qellyka        "
  echo "==================================================="
  echo ""
}

#################################
# PRE-FLIGHT
#################################
[[ $EUID -eq 0 ]] || die "Запускать нужно от root"
. /etc/os-release
[[ "$ID" == "ubuntu" || "$ID" == "debian" ]] || die "Поддерживаются только Ubuntu/Debian (обнаружено: $ID)"

banner

#################################
# INTERACTIVE: full install or just seed a profile
#################################
echo "Что делаем?"
echo ""
echo "  1) Установить панель (полная установка)"
echo "  2) Только создать Config Profile с 4 базовыми инбаундами"
echo "     (панель уже установлена — своя или через этот же скрипт ранее)"
echo ""
read -rp "Введите номер [1-2]: " TOP_CHOICE
case "$TOP_CHOICE" in
  1) TOP_MODE="install" ;;
  2) TOP_MODE="seed_only" ;;
  *) die "Некорректный выбор" ;;
esac
echo ""

#################################
# COMMON HELPERS
#################################
install_base() {
  log "Обновляю систему..."
  export DEBIAN_FRONTEND=noninteractive
  apt update -qq
  apt upgrade -y -qq
  apt install -y -qq curl openssl jq nftables dnsutils

  if command -v ufw >/dev/null 2>&1 && LC_ALL=C ufw status 2>/dev/null | grep -q "Status: active"; then
    warn "UFW активен — отключаю в пользу nftables"
    ufw --force disable >/dev/null 2>&1 || true
  fi

  if ! command -v docker >/dev/null 2>&1; then
    log "Устанавливаю Docker..."
    curl -fsSL https://get.docker.com | sh
  fi
  docker compose version >/dev/null 2>&1 || die "Docker Compose plugin недоступен после установки"
}

write_nftables_base() {
  log "Записываю базовые правила nftables..."
  [[ -f /etc/nftables.conf ]] && cp /etc/nftables.conf "/etc/nftables.conf.bak.$(date +%s)"

  local icmp_rule="        icmp type echo-request accept"
  if [[ "${BLOCK_ICMP:-false}" == true ]]; then
    icmp_rule="        # ICMP echo-request blocked (--block-icmp)"
  fi

  cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# Generated by remnawave-deploy.sh — by qellyka
#
# IMPORTANT: only ever flush OUR OWN table (inet filter), never the whole
# ruleset. Docker keeps its own port-publishing (DNAT) rules in a separate
# table (ip nat) — a global "flush ruleset" wipes those out too and breaks
# every published container port on the host, including ones already
# running. "table inet filter {}" makes the flush below a no-op (rather
# than an error) the very first time this runs, before the table exists.
table inet filter {}
flush table inet filter

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state invalid drop
        ct state established,related accept
        iif lo accept
        tcp dport $SSH_PORT accept
$icmp_rule
${EXTRA_INPUT_RULES:-}
    }
    chain forward {
        type filter hook forward priority filter; policy drop;
    }
    chain output {
        type filter hook output priority filter; policy accept;
    }
}
EOF
  nft -c -f /etc/nftables.conf || die "Синтаксическая ошибка nftables — проверь /etc/nftables.conf"
  nft -f /etc/nftables.conf
  systemctl enable nftables >/dev/null 2>&1 || true
  systemctl restart nftables
}

generate_reality_keys() {
  # Populates REALITY_PRIVATE_KEY / REALITY_PUBLIC_KEY / REALITY_SHORTID
  if ! command -v xray >/dev/null 2>&1; then
    log "Устанавливаю Xray-core (только для генерации ключей Reality)..."
    bash -c "$(curl -Ls https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh)" @ install >/dev/null 2>&1
  fi
  local keys
  keys=$(xray x25519)
  REALITY_PRIVATE_KEY=$(echo "$keys" | grep -i "Private" | awk '{print $NF}')
  REALITY_PUBLIC_KEY=$(echo "$keys" | grep -i "Public" | awk '{print $NF}')
  REALITY_SHORTID=$(openssl rand -hex 8)
  [[ -n "$REALITY_PRIVATE_KEY" && -n "$REALITY_PUBLIC_KEY" ]] || die "Не удалось сгенерировать ключи Reality"
}

generate_hy2_cert() {
  mkdir -p /etc/xray-certs
  if [[ ! -f /etc/xray-certs/hy2-cert.crt ]]; then
    openssl req -x509 -nodes -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
      -keyout /etc/xray-certs/hy2-key.pem \
      -out /etc/xray-certs/hy2-cert.crt \
      -days 3650 -subj "/CN=www.bing.com" >/dev/null 2>&1
  fi
}

write_nginx_hardening() {
  # Shared SSL/gzip snippet — one place, included by every server block that needs it.
  mkdir -p /etc/nginx/snippets
  cat > /etc/nginx/snippets/ssl-params.conf <<'EOF'
ssl_protocols          TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 valid=60s;
resolver_timeout 2s;

gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_min_length 256;
gzip_types
    application/atom+xml application/geo+json application/javascript
    application/x-javascript application/json application/ld+json
    application/manifest+json application/rdf+xml application/rss+xml
    application/xhtml+xml application/xml application/wasm
    font/eot font/otf font/ttf image/svg+xml
    text/css text/javascript text/plain text/xml;
EOF

  # Any TLS connection with an SNI that doesn't match a configured server_name
  # gets the handshake dropped outright, instead of falling through to some
  # default vhost or error page — gives a port-scanner nothing to work with.
  cat > /etc/nginx/sites-available/00-reject-unknown-sni <<'EOF'
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    ssl_reject_handshake on;
}
EOF
  ln -sf /etc/nginx/sites-available/00-reject-unknown-sni /etc/nginx/sites-enabled/
}

issue_cert_for_domain() {
  local domain="$1"
  log "Проверяю DNS для $domain..."
  local resolved public_ip
  resolved=$(dig +short "$domain" A | tail -n1 || true)
  public_ip=$(curl -s -4 --max-time 5 https://api.ipify.org || true)
  if [[ -z "$resolved" ]]; then
    warn "$domain пока не резолвится. Certbot, скорее всего, не пройдёт, пока не создашь A-запись -> $public_ip"
  elif [[ "$resolved" != "$public_ip" ]]; then
    warn "$domain резолвится в $resolved, а не в IP этого сервера ($public_ip). Certbot может не пройти."
  fi

  if [[ ! -d "/etc/letsencrypt/live/$domain" ]]; then
    mkdir -p /var/www/certbot
    cat > "/etc/nginx/sites-available/$domain.bootstrap" <<EOF
server {
    listen 80;
    server_name $domain;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 404; }
}
EOF
    ln -sf "/etc/nginx/sites-available/$domain.bootstrap" "/etc/nginx/sites-enabled/$domain.bootstrap"
    nginx -t && systemctl reload nginx

    certbot certonly --webroot -w /var/www/certbot -d "$domain" --non-interactive --agree-tos \
      -m "admin@$domain" --no-eff-email || warn "Certbot не смог получить сертификат для $domain — поправь DNS и запусти certbot вручную позже"

    rm -f "/etc/nginx/sites-enabled/$domain.bootstrap" "/etc/nginx/sites-available/$domain.bootstrap"
  else
    log "Сертификат для $domain уже есть — пропускаю выпуск."
  fi
}

#################################
# PANEL-SPECIFIC
#################################
write_bootstrap_script() {
  cat > /opt/remnawave/remnawave_bootstrap.py <<'PYEOF'
#!/usr/bin/env python3
"""
Remnawave panel bootstrap — by qellyka
Registers the first admin account (only works if no admin exists yet).

API-token creation was intentionally NOT automated here: creating a token
via the API immediately after an API-based registration consistently
returns 403 in practice, even though creating one through the panel UI
with the same freshly-registered account works fine. Root cause unclear —
rather than keep guessing against a live install, the token is created by
hand in the UI and handed back to the deploy script.
"""
import json
import os
import sys
import time
import urllib.request
import urllib.error

PANEL_URL = os.environ.get("RW_PANEL_URL", "")
ADMIN_USERNAME = os.environ.get("RW_ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.environ.get("RW_ADMIN_PASSWORD", "")

if not all([PANEL_URL, ADMIN_USERNAME, ADMIN_PASSWORD]):
    print("[ERROR] Missing RW_PANEL_URL / RW_ADMIN_USERNAME / RW_ADMIN_PASSWORD", file=sys.stderr)
    sys.exit(1)


def call(method, path, token=None, body=None):
    url = PANEL_URL.rstrip("/") + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode())


status = None
for attempt in range(15):
    try:
        status = call("GET", "/api/auth/status")
        break
    except (urllib.error.URLError, urllib.error.HTTPError):
        time.sleep(2)
if status is None:
    print("[ERROR] Panel did not become reachable in time", file=sys.stderr)
    sys.exit(1)

if not status["response"]["isRegisterAllowed"]:
    print("[SKIP] Registration is not open (an admin already exists).", file=sys.stderr)
    sys.exit(2)

call("POST", "/api/auth/register", body={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD})
print(f"ADMIN_USERNAME={ADMIN_USERNAME}")
PYEOF
}

write_seed_profile_script() {
  cat > /opt/remnawave/remnawave_seed_profile.py <<'SEEDEOF'
#!/usr/bin/env python3
"""
Remnawave — seed a Config Profile with the 4 base inbound presets — by qellyka
Creates ONLY a Config Profile (Reality+TCP, Reality+gRPC, Reality+XHTTP,
Hysteria2) — no Node, no Host. Meant to be run from the PANEL install script,
before any node exists, so a ready-to-pick profile is already there once you
get to setting up your first node.

The CDN inbound is deliberately NOT included here — it's tied to a specific
node's domain/origin, which isn't known yet at panel-install time. It's
still created per-node, same as before.

Hysteria2's certificate is always embedded inline (never a file path) — this
script has no reason to assume it's running on the same machine as any future
node, so a filesystem-path reference would never resolve there anyway.
"""
import json
import os
import sys
import urllib.request
import urllib.error


def die(msg):
    print(f"[ERROR] {msg}", file=sys.stderr)
    sys.exit(1)


def api(method, path, token, body=None):
    url = PANEL_URL.rstrip("/") + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode(errors="replace")
        die(f"{method} {path} -> HTTP {e.code}: {body_text}")
    except urllib.error.URLError as e:
        die(f"{method} {path} -> connection failed: {e}")


PANEL_URL = os.environ.get("RW_PANEL_URL", "")
API_TOKEN = os.environ.get("RW_API_TOKEN", "")
PROFILE_NAME = os.environ.get("RW_PROFILE_NAME", "base-4-preset")

REQUIRED = [
    "RW_REALITY_TCP_PORT", "RW_REALITY_TCP_SNI", "RW_REALITY_TCP_PRIVATE_KEY", "RW_REALITY_TCP_SHORTID",
    "RW_REALITY_GRPC_PORT", "RW_REALITY_GRPC_SNI", "RW_REALITY_GRPC_PRIVATE_KEY", "RW_REALITY_GRPC_SHORTID",
    "RW_REALITY_GRPC_SERVICE_NAME",
    "RW_REALITY_XHTTP_PORT", "RW_REALITY_XHTTP_SNI", "RW_REALITY_XHTTP_PRIVATE_KEY", "RW_REALITY_XHTTP_SHORTID",
    "RW_REALITY_XHTTP_PATH",
    "RW_HY2_PORT", "RW_HY2_CERT_PEM", "RW_HY2_KEY_PEM",
]
missing = [v for v in ["RW_PANEL_URL", "RW_API_TOKEN"] + REQUIRED if not os.environ.get(v)]
if missing:
    die(f"Missing required env vars: {', '.join(missing)}")

inbounds = [
    {
        "tag": "reality-tcp",
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_REALITY_TCP_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
                "show": False, "xver": 0,
                "target": f"{os.environ['RW_REALITY_TCP_SNI']}:443",
                "serverNames": [os.environ["RW_REALITY_TCP_SNI"]],
                "privateKey": os.environ["RW_REALITY_TCP_PRIVATE_KEY"],
                "shortIds": [os.environ["RW_REALITY_TCP_SHORTID"]]
            }
        }
    },
    {
        "tag": "reality-grpc",
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_REALITY_GRPC_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "grpc",
            "security": "reality",
            "grpcSettings": {"serviceName": os.environ["RW_REALITY_GRPC_SERVICE_NAME"], "multiMode": False},
            "realitySettings": {
                "show": False, "xver": 0,
                "target": f"{os.environ['RW_REALITY_GRPC_SNI']}:443",
                "serverNames": [os.environ["RW_REALITY_GRPC_SNI"]],
                "privateKey": os.environ["RW_REALITY_GRPC_PRIVATE_KEY"],
                "shortIds": [os.environ["RW_REALITY_GRPC_SHORTID"]]
            }
        }
    },
    {
        "tag": "reality-xhttp",
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_REALITY_XHTTP_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "xhttp",
            "security": "reality",
            "realitySettings": {
                "show": False, "xver": 0,
                "target": f"{os.environ['RW_REALITY_XHTTP_SNI']}:443",
                "serverNames": [os.environ["RW_REALITY_XHTTP_SNI"]],
                "privateKey": os.environ["RW_REALITY_XHTTP_PRIVATE_KEY"],
                "shortIds": [os.environ["RW_REALITY_XHTTP_SHORTID"]]
            },
            "xhttpSettings": {
                "path": os.environ["RW_REALITY_XHTTP_PATH"],
                "mode": "auto",
                "xPaddingBytes": "100-1000"
            }
        }
    },
    {
        "tag": "hysteria2",
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_HY2_PORT"]),
        "protocol": "hysteria",
        "settings": {"version": 2, "clients": []},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "hysteria",
            "security": "tls",
            "tlsSettings": {
                "alpn": ["h3"], "minVersion": "1.3", "maxVersion": "1.3",
                "certificates": [{
                    "certificate": os.environ["RW_HY2_CERT_PEM"].splitlines(),
                    "key": os.environ["RW_HY2_KEY_PEM"].splitlines()
                }]
            },
            "hysteriaSettings": {
                "version": 2, "udpIdleTimeout": 60,
                "masquerade": {"type": "proxy", "url": os.environ.get("RW_HY2_MASQUERADE_URL", "https://www.bing.com"), "rewriteHost": True}
            }
        }
    },
]

print("[1/2] Verifying API token...")
api("GET", "/api/hosts", API_TOKEN)
print("      OK.")

print("[2/2] Creating Config Profile with 4 base inbounds...")
profile_body = {
    "name": PROFILE_NAME,
    "config": {
        "inbounds": inbounds,
        "outbounds": [{"protocol": "freedom", "tag": "direct"}]
    }
}
profile_resp = api("POST", "/api/config-profiles", API_TOKEN, profile_body)["response"]
profile_uuid = profile_resp["uuid"]
print(f"      Profile UUID: {profile_uuid}")
for ib in profile_resp["inbounds"]:
    print(f"      Inbound '{ib['tag']}' UUID: {ib['uuid']}")

print()
print("=====================================================")
print(f"Done. Profile '{PROFILE_NAME}' created: {profile_uuid}")
print("Pick it from the node install script's 'reuse existing profile' option.")
print("=====================================================")
SEEDEOF
}

# Generates fresh keys/cert for the 4 base presets and calls the seed script.
# Takes panel URL and API token as arguments — works whether called from a
# full install (URL/token already known) or standalone (asked for directly).
seed_base_profile() {
  local panel_url="$1" token="$2"
  apt install -y -qq python3
  generate_reality_keys
  local tcp_priv="$REALITY_PRIVATE_KEY" tcp_sid="$REALITY_SHORTID"
  generate_reality_keys
  local grpc_priv="$REALITY_PRIVATE_KEY" grpc_sid="$REALITY_SHORTID"
  generate_reality_keys
  local xhttp_priv="$REALITY_PRIVATE_KEY" xhttp_sid="$REALITY_SHORTID"
  generate_hy2_cert
  local hy2_cert hy2_key
  hy2_cert=$(cat /etc/xray-certs/hy2-cert.crt)
  hy2_key=$(cat /etc/xray-certs/hy2-key.pem)
  write_seed_profile_script

  env \
    RW_PANEL_URL="$panel_url" RW_API_TOKEN="$token" \
    RW_REALITY_TCP_PORT=443 RW_REALITY_TCP_SNI=yandex.ru \
    RW_REALITY_TCP_PRIVATE_KEY="$tcp_priv" RW_REALITY_TCP_SHORTID="$tcp_sid" \
    RW_REALITY_GRPC_PORT=8443 RW_REALITY_GRPC_SNI=yandex.ru \
    RW_REALITY_GRPC_PRIVATE_KEY="$grpc_priv" RW_REALITY_GRPC_SHORTID="$grpc_sid" \
    RW_REALITY_GRPC_SERVICE_NAME="$(openssl rand -hex 6)" \
    RW_REALITY_XHTTP_PORT=2053 RW_REALITY_XHTTP_SNI=yandex.ru \
    RW_REALITY_XHTTP_PRIVATE_KEY="$xhttp_priv" RW_REALITY_XHTTP_SHORTID="$xhttp_sid" \
    RW_REALITY_XHTTP_PATH="/$(openssl rand -hex 8)/" \
    RW_HY2_PORT=8444 RW_HY2_CERT_PEM="$hy2_cert" RW_HY2_KEY_PEM="$hy2_key" \
    python3 /opt/remnawave/remnawave_seed_profile.py \
    || warn "Не удалось создать профиль."
}

install_panel() {
  echo "Перед этим шагом нужны две A-записи в DNS, указывающие на IP этого сервера:"
  echo "  - домен для панели (например panel.example.com)"
  echo "  - домен для страницы подписки (например sub.example.com)"
  echo "Если уже создал — просто продолжай, ничего страшного, если ещё нет — сделай это"
  echo "в панели DNS у регистратора прямо сейчас (займёт минуту), потом возвращайся."
  echo "Скрипт сам проверит, резолвятся ли они правильно, перед выпуском сертификатов."
  echo ""
  read_domain "Домен для панели администратора (например panel.example.com): " PANEL_DOMAIN
  read_domain "Домен для страницы подписки (например sub.example.com): " SUB_DOMAIN
  read -rp "Порт SSH, который нельзя закрывать [22]: " SSH_PORT
  SSH_PORT=${SSH_PORT:-22}
  [[ -n "$PANEL_DOMAIN" && -n "$SUB_DOMAIN" ]] || die "Оба домена обязательны"
  echo ""

  install_base
  apt install -y -qq nginx certbot

  mkdir -p /opt/remnawave
  cd /opt/remnawave

  if [[ -f .env && -f docker-compose.yml ]]; then
    log ".env уже существует — повторный запуск, секреты не трогаю (иначе пароль Postgres"
    log "разойдётся с уже инициализированной базой, и панель уйдёт в цикл рестартов)."
    PG_PW=$(grep "^POSTGRES_PASSWORD=" .env | cut -d= -f2-)
    grep -q "^FRONT_END_DOMAIN=" .env && sed -i "s/^FRONT_END_DOMAIN=.*/FRONT_END_DOMAIN=$PANEL_DOMAIN/" .env
    grep -q "^SUB_PUBLIC_DOMAIN=" .env && sed -i "s/^SUB_PUBLIC_DOMAIN=.*/SUB_PUBLIC_DOMAIN=$SUB_DOMAIN/" .env
  else
    log "Скачиваю официальные шаблоны docker-compose и .env..."
    curl -fsSL -o docker-compose.yml https://raw.githubusercontent.com/remnawave/backend/refs/heads/main/docker-compose-prod.yml
    curl -fsSL -o .env https://raw.githubusercontent.com/remnawave/backend/refs/heads/main/.env.sample

    log "Генерирую секреты..."
    sed -i "s/^APP_SECRET=.*/APP_SECRET=$(openssl rand -hex 64)/" .env
    sed -i "s/^JWT_AUTH_SECRET=.*/JWT_AUTH_SECRET=$(openssl rand -hex 64)/" .env
    sed -i "s/^JWT_API_TOKENS_SECRET=.*/JWT_API_TOKENS_SECRET=$(openssl rand -hex 64)/" .env
    sed -i "s/^METRICS_PASS=.*/METRICS_PASS=$(openssl rand -hex 64)/" .env
    sed -i "s/^WEBHOOK_SECRET_HEADER=.*/WEBHOOK_SECRET_HEADER=$(openssl rand -hex 64)/" .env
    PG_PW=$(openssl rand -hex 24)
    sed -i "s/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$PG_PW/" .env
    sed -i "s|^\(DATABASE_URL=\"postgresql://postgres:\)[^@]*\(@.*\)|\1$PG_PW\2|" .env
    grep -q "^FRONT_END_DOMAIN=" .env && sed -i "s/^FRONT_END_DOMAIN=.*/FRONT_END_DOMAIN=$PANEL_DOMAIN/" .env
    grep -q "^SUB_PUBLIC_DOMAIN=" .env && sed -i "s/^SUB_PUBLIC_DOMAIN=.*/SUB_PUBLIC_DOMAIN=$SUB_DOMAIN/" .env
  fi

  log "Запускаю контейнеры панели..."
  docker compose up -d

  issue_cert_for_domain "$PANEL_DOMAIN"
  issue_cert_for_domain "$SUB_DOMAIN"

  write_nginx_hardening

  log "Пишу конфиги Nginx..."
  if [[ -d "/etc/letsencrypt/live/$PANEL_DOMAIN" ]]; then
    cat > /etc/nginx/sites-available/remnawave-panel <<EOF
server {
    listen 80; server_name $PANEL_DOMAIN;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl; http2 on; server_name $PANEL_DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$PANEL_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$PANEL_DOMAIN/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
EOF
  else
    warn "Сертификата для $PANEL_DOMAIN нет — пишу временный HTTP-конфиг без HTTPS."
    cat > /etc/nginx/sites-available/remnawave-panel <<EOF
server {
    listen 80; server_name $PANEL_DOMAIN;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 503 'Сертификат ещё не выпущен — перезапусти certbot вручную.'; }
}
EOF
  fi

  if [[ -d "/etc/letsencrypt/live/$SUB_DOMAIN" ]]; then
    cat > /etc/nginx/sites-available/remnawave-sub <<EOF
server {
    listen 80; server_name $SUB_DOMAIN;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl; http2 on; server_name $SUB_DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$SUB_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$SUB_DOMAIN/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    location / {
        proxy_pass http://127.0.0.1:3010;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF
  else
    warn "Сертификата для $SUB_DOMAIN нет — пишу временный HTTP-конфиг без HTTPS."
    cat > /etc/nginx/sites-available/remnawave-sub <<EOF
server {
    listen 80; server_name $SUB_DOMAIN;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 503 'Сертификат ещё не выпущен — перезапусти certbot вручную.'; }
}
EOF
  fi
  ln -sf /etc/nginx/sites-available/remnawave-panel /etc/nginx/sites-enabled/
  ln -sf /etc/nginx/sites-available/remnawave-sub /etc/nginx/sites-enabled/
  rm -f /etc/nginx/sites-enabled/default
  nginx -t && systemctl reload nginx
  if [[ ! -d "/etc/letsencrypt/live/$PANEL_DOMAIN" || ! -d "/etc/letsencrypt/live/$SUB_DOMAIN" ]]; then
    warn "Один или оба домена работают пока без HTTPS (см. предупреждения выше)."
    warn "Когда лимит Let's Encrypt снимется (сообщение certbot указывает точное время),"
    warn "запусти: certbot certonly --webroot -w /var/www/certbot -d ДОМЕН, затем"
    warn "перезапусти установку панели ещё раз — она сама допишет нормальный HTTPS-конфиг."
  fi

  EXTRA_INPUT_RULES="        tcp dport { 80, 443 } accept"
  write_nftables_base

  echo ""
  echo "Создать первого администратора автоматически, прямо сейчас?"
  echo "  1) Да (работает только для только что установленной, ещё пустой панели)"
  echo "  2) Нет — сделаю сам в UI позже (страницу подписки придётся донастроить вручную)"
  read -rp "Введите номер [1-2]: " BOOTSTRAP_CHOICE
  BOOTSTRAP_OK=false
  ADMIN_CREATED=false
  if [[ "$BOOTSTRAP_CHOICE" == "1" ]]; then
    read -rp "Логин администратора: " RW_ADMIN_USERNAME
    RW_ADMIN_PASSWORD=$(openssl rand -base64 18)
    apt install -y -qq python3
    write_bootstrap_script
    BOOTSTRAP_OUT=$(RW_PANEL_URL="https://$PANEL_DOMAIN" RW_ADMIN_USERNAME="$RW_ADMIN_USERNAME" RW_ADMIN_PASSWORD="$RW_ADMIN_PASSWORD" \
      python3 /opt/remnawave/remnawave_bootstrap.py 2>&1)
    echo "$BOOTSTRAP_OUT" | grep -q "^ADMIN_USERNAME=" && ADMIN_CREATED=true

    if [[ "$ADMIN_CREATED" == true ]]; then
      echo "ADMIN_USERNAME=$RW_ADMIN_USERNAME" > /opt/remnawave/bootstrap-credentials.txt
      echo "ADMIN_PASSWORD=$RW_ADMIN_PASSWORD" >> /opt/remnawave/bootstrap-credentials.txt
      chmod 600 /opt/remnawave/bootstrap-credentials.txt

      echo ""
      log "Администратор создан:"
      echo "  Логин:  $RW_ADMIN_USERNAME"
      echo "  Пароль: $RW_ADMIN_PASSWORD"
      echo "(сохранено в /opt/remnawave/bootstrap-credentials.txt, chmod 600)"
      echo ""
      echo "Создание токена через API у нас пока не работает надёжно (стабильно"
      echo "получаем 403 сразу после регистрации, хотя через UI создаётся без проблем)."
      echo "Зайди в панель — https://$PANEL_DOMAIN — под этими данными,"
      echo "создай токен: Settings -> API Tokens -> Create (шаблон под страницу"
      echo "подписки подходит — не обязательно давать полные права)."
      echo "Вставь готовый токен сюда."
      echo "(Enter без значения — пропустить, донастроишь подписку вручную позже)"
      read -rp "API-токен: " API_TOKEN_VALUE
      if [[ -n "$API_TOKEN_VALUE" ]]; then
        HTTP_CODE=$(curl -fsS -o /dev/null -w "%{http_code}" \
          -H "Authorization: Bearer $API_TOKEN_VALUE" "https://$PANEL_DOMAIN/api/hosts" || true)
        # 200 = полный доступ, 403 = токен настоящий и принят сервером, просто
        # без прав именно на управление хостами (например, создан по шаблону
        # конкретно под страницу подписки, с урезанными правами — это нормально
        # и ожидаемо, не признак битого токена). Только 401 значит, что сервер
        # вообще не признал токен — вот это уже похоже на опечатку при вставке.
        if [[ "$HTTP_CODE" == "200" || "$HTTP_CODE" == "403" ]]; then
          BOOTSTRAP_OK=true
          log "Токен принят сервером."
        elif [[ "$HTTP_CODE" == "401" ]]; then
          warn "Токен не прошёл проверку (401 — не распознан) — возможно, опечатка при вставке."
          warn "Страница подписки не получит REMNAWAVE_API_TOKEN автоматически."
        else
          warn "Не удалось проверить токен (код ответа: $HTTP_CODE) — сохраняю как есть,"
          warn "но сверь вручную, если страница подписки не заработает."
          BOOTSTRAP_OK=true
        fi
      fi
    else
      warn "Автосоздание администратора не удалось (см. вывод ниже) — создай его вручную через UI."
      echo "$BOOTSTRAP_OUT"
    fi
  fi

  echo ""
  echo "Создать Config Profile с 4 базовыми инбаундами прямо сейчас?"
  echo "Это чтобы при установке первой ноды было что сразу переиспользовать,"
  echo "а не создавать инбаунды с нуля отдельно для каждой ноды."
  echo "  1) Да (нужен API-токен — тот же, что и для страницы подписки)"
  echo "  2) Нет — создам позже, при установке ноды"
  read -rp "Введите номер [1-2]: " SEED_CHOICE
  if [[ "$SEED_CHOICE" == "1" ]]; then
    SEED_TOKEN="${API_TOKEN_VALUE:-}"
    if [[ -z "$SEED_TOKEN" ]]; then
      echo "Автобутстрап не дал токен — вставь его сам (Settings -> API Tokens в панели):"
      read -rp "API-токен: " SEED_TOKEN
    fi
    if [[ -n "$SEED_TOKEN" ]]; then
      seed_base_profile "https://$PANEL_DOMAIN" "$SEED_TOKEN"
    else
      warn "Токен не введён — профиль не создан."
    fi
  fi

  log "Разворачиваю сервер подписки..."
  mkdir -p /opt/remnawave/subscription
  cat > /opt/remnawave/subscription/docker-compose.yml <<'EOF'
services:
  remnawave-subscription-page:
    image: remnawave/subscription-page:latest
    container_name: remnawave-subscription-page
    hostname: remnawave-subscription-page
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:3010:3010'
    networks:
      - remnawave-network
networks:
  remnawave-network:
    external: true
EOF
  cat > /opt/remnawave/subscription/.env <<EOF
APP_PORT=3010
REMNAWAVE_PANEL_URL=http://remnawave:3000
REMNAWAVE_API_TOKEN=${API_TOKEN_VALUE:-}
CUSTOM_SUB_PREFIX=
MARZBAN_LEGACY_LINK_ENABLED=false
MARZBAN_LEGACY_SECRET_KEY=
TRUST_PROXY=1
EOF
  if [[ "$BOOTSTRAP_OK" != true ]]; then
    warn "REMNAWAVE_API_TOKEN оставлен пустым в /opt/remnawave/subscription/.env"
    warn "Создай токен вручную (Settings -> API Tokens), впиши его туда, затем:"
    warn "  cd /opt/remnawave/subscription && docker compose up -d"
  fi
  cd /opt/remnawave/subscription
  docker compose up -d
  cd /opt/remnawave


  echo ""
  echo "==================================================="
  log "Панель установлена."
  echo "==================================================="
  echo "Панель:        https://$PANEL_DOMAIN"
  echo "Подписка:      https://$SUB_DOMAIN"
  echo "Пароль Postgres (также в /opt/remnawave/.env): $PG_PW"
  if [[ "$BOOTSTRAP_OK" == true ]]; then
    echo ""
    echo "Администратор создан, токен подтверждён и передан странице подписки:"
    echo "  Логин:  $RW_ADMIN_USERNAME"
    echo "  Пароль: $RW_ADMIN_PASSWORD"
    echo "  API-токен: $API_TOKEN_VALUE"
    echo "(сохранено в /opt/remnawave/bootstrap-credentials.txt, chmod 600)"
    echo ""
    echo "Можешь сразу запускать этот же скрипт в режиме ноды и вставить"
    echo "этот URL панели + этот API-токен при автопровижининге."
  elif [[ "$ADMIN_CREATED" == true ]]; then
    echo ""
    warn "Администратор создан, но токен не был передан (пропущен или не прошёл проверку)."
    echo "  Логин:  $RW_ADMIN_USERNAME"
    echo "  Пароль: $RW_ADMIN_PASSWORD"
    echo "(сохранено в /opt/remnawave/bootstrap-credentials.txt, chmod 600)"
    echo "Создай токен в панели (Settings -> API Tokens -> Create), впиши в"
    echo "/opt/remnawave/subscription/.env и перезапусти: docker compose up -d"
  else
    echo ""
    echo "Дальше: зайди в панель, создай админа, потом"
    echo "Settings -> API Tokens, чтобы получить токен для режима ноды."
  fi
  echo "==================================================="
}

if [[ "$TOP_MODE" == "seed_only" ]]; then
  read_domain "URL панели без https:// (например panel.example.com): " SEED_PANEL_HOST
  read -rp "API-токен: " SEED_ONLY_TOKEN
  [[ -n "$SEED_ONLY_TOKEN" ]] || die "Токен обязателен"
  apt-get update -qq >/dev/null 2>&1 || true
  apt-get install -y -qq curl openssl jq nftables python3 >/dev/null 2>&1
  mkdir -p /opt/remnawave
  seed_base_profile "https://$SEED_PANEL_HOST" "$SEED_ONLY_TOKEN"
else
  install_panel
fi
