#!/usr/bin/env bash
# Remnawave deploy script — Nginx + nftables edition, interactive installer
# by qellyka
#
# NOTE on the write_*_script() functions below (write_provision_script,
# write_bootstrap_script, write_list_nodes_script): these embed small Python
# helper scripts as heredocs. They are self-contained — this ONE file (plus
# decoy-cdn/index.html) is everything that needs to live in the GitHub repo.
# The Python helpers write themselves to disk automatically at runtime; you
# never need to upload or manage them separately.
set -euo pipefail

trap 'echo -e "\033[1;31m[ERROR]\033[0m Error at line $LINENO"; exit 1' ERR
log()  { echo -e "\033[1;32m[INFO]\033[0m $1"; }
warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }
die()  { echo -e "\033[1;31m[ERROR]\033[0m $1"; exit 1; }

# Reads a domain name and validates it, re-prompting on anything that doesn't
# look like a clean hostname. Strips to only valid domain characters first —
# this silently drops stray bytes from terminal/paste corruption (garbled
# copy-paste, keyboard-layout artifacts, etc.) rather than letting them
# propagate into DNS lookups, certbot, and Nginx configs downstream, where
# they show up as confusing failures far from the actual cause.
read_domain() {
  local prompt="$1" __resultvar="$2" value
  while true; do
    read -rp "$prompt" value
    value=$(printf '%s' "$value" | tr -cd 'a-zA-Z0-9.-')
    if [[ "$value" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$ ]]; then
      printf -v "$__resultvar" '%s' "$value"
      return 0
    fi
    warn "Похоже на некорректный домен — возможно, при вводе/вставке приклеился"
    warn "случайный символ (например от переключения раскладки). Введи ещё раз."
  done
}

# Placeholder — will point to a real repo of pre-built inbound templates
# once we build it together. Kept as a variable so it's a one-line change later.
INBOUNDS_REPO_URL="https://raw.githubusercontent.com/qellyka/remnawave-installer/main/remnawave-inbounds"
DECOY_SITE_URL="https://raw.githubusercontent.com/qellyka/remnawave-installer/main/index.html"

#################################
# BANNER
#################################
banner() {
  clear
  echo "==================================================="
  echo "    ____  ________  ____   _____ _       _____ _    ________"
  echo "   / __ \\/ ____/  |/  / | / /   | |     / /   | |  / / ____/"
  echo "  / /_/ / __/ / /|_/ /  |/ / /| | | /| / / /| | | / / __/   "
  echo " / _, _/ /___/ /  / / /|  / ___ | |/ |/ / ___ | |/ / /___   "
  echo "/_/ |_/_____/_/  /_/_/ |_/_/  |_|__/|__/_/  |_|___/_____/   "
  echo ""
  echo "        DEPLOY SCRIPT (Nginx + nftables) — by qellyka        "
  echo "==================================================="
  echo ""
}

#################################
# PRE-FLIGHT
#################################
[[ $EUID -eq 0 ]] || die "Запускать нужно от root"
. /etc/os-release
[[ "$ID" == "ubuntu" || "$ID" == "debian" ]] || die "Поддерживаются только Ubuntu/Debian (обнаружено: $ID)"

banner

#################################
# INTERACTIVE: mode selection
#################################
echo "Что вы хотите установить?"
echo ""
echo "  1) Панель Remnawave (Panel)"
echo "  2) Ноду Remnawave (Node) — с нуля, ставим агента на новый сервер"
echo "  3) Наши инбаунды на уже существующую ноду (агент уже подключён к панели)"
echo ""
read -rp "Введите номер [1-3]: " MODE_CHOICE
case "$MODE_CHOICE" in
  1) MODE="panel" ;;
  2) MODE="node"; EXISTING_NODE=false ;;
  3) MODE="node"; EXISTING_NODE=true ;;
  *) die "Некорректный выбор" ;;
esac
echo ""

# Место для будущих режимов (naiveproxy, mieru, olcRTC и т.д.) — когда появятся
# свои управляющие скрипты для них, здесь добавится пункт 4), 5)...

#################################
# COMMON HELPERS
#################################
install_base() {
  log "Обновляю систему..."
  export DEBIAN_FRONTEND=noninteractive
  apt update -qq
  apt upgrade -y -qq
  apt install -y -qq curl openssl jq nftables dnsutils

  if command -v ufw >/dev/null 2>&1 && LC_ALL=C ufw status 2>/dev/null | grep -q "Status: active"; then
    warn "UFW активен — отключаю в пользу nftables"
    ufw --force disable >/dev/null 2>&1 || true
  fi

  if ! command -v docker >/dev/null 2>&1; then
    log "Устанавливаю Docker..."
    curl -fsSL https://get.docker.com | sh
  fi
  docker compose version >/dev/null 2>&1 || die "Docker Compose plugin недоступен после установки"
}

write_nftables_base() {
  log "Записываю базовые правила nftables..."
  [[ -f /etc/nftables.conf ]] && cp /etc/nftables.conf "/etc/nftables.conf.bak.$(date +%s)"

  local icmp_rule="        icmp type echo-request accept"
  if [[ "${BLOCK_ICMP:-false}" == true ]]; then
    icmp_rule="        # ICMP echo-request blocked (--block-icmp)"
  fi

  cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# Generated by remnawave-deploy.sh — by qellyka
#
# IMPORTANT: only ever flush OUR OWN table (inet filter), never the whole
# ruleset. Docker keeps its own port-publishing (DNAT) rules in a separate
# table (ip nat) — a global "flush ruleset" wipes those out too and breaks
# every published container port on the host, including ones already
# running. "table inet filter {}" makes the flush below a no-op (rather
# than an error) the very first time this runs, before the table exists.
table inet filter {}
flush table inet filter

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state invalid drop
        ct state established,related accept
        iif lo accept
        tcp dport $SSH_PORT accept
$icmp_rule
${EXTRA_INPUT_RULES:-}
    }
    chain forward {
        type filter hook forward priority filter; policy drop;
    }
    chain output {
        type filter hook output priority filter; policy accept;
    }
}
EOF
  nft -c -f /etc/nftables.conf || die "Синтаксическая ошибка nftables — проверь /etc/nftables.conf"
  nft -f /etc/nftables.conf
  systemctl enable nftables >/dev/null 2>&1 || true
  systemctl restart nftables
}

generate_reality_keys() {
  # Populates REALITY_PRIVATE_KEY / REALITY_PUBLIC_KEY / REALITY_SHORTID
  if ! command -v xray >/dev/null 2>&1; then
    log "Устанавливаю Xray-core (только для генерации ключей Reality)..."
    bash -c "$(curl -Ls https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh)" @ install >/dev/null 2>&1
  fi
  local keys
  keys=$(xray x25519)
  REALITY_PRIVATE_KEY=$(echo "$keys" | grep -i "Private" | awk '{print $NF}')
  REALITY_PUBLIC_KEY=$(echo "$keys" | grep -i "Public" | awk '{print $NF}')
  REALITY_SHORTID=$(openssl rand -hex 8)
  [[ -n "$REALITY_PRIVATE_KEY" && -n "$REALITY_PUBLIC_KEY" ]] || die "Не удалось сгенерировать ключи Reality"
}

generate_hy2_cert() {
  mkdir -p /etc/xray-certs
  if [[ ! -f /etc/xray-certs/hy2-cert.crt ]]; then
    openssl req -x509 -nodes -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
      -keyout /etc/xray-certs/hy2-key.pem \
      -out /etc/xray-certs/hy2-cert.crt \
      -days 3650 -subj "/CN=www.bing.com" >/dev/null 2>&1
  fi
}

write_decoy_site() {
  mkdir -p /var/www/decoy-cdn
  if curl -fsSL "$DECOY_SITE_URL" -o /var/www/decoy-cdn/index.html 2>/dev/null && [[ -s /var/www/decoy-cdn/index.html ]]; then
    log "Заглушка-камуфляж скачана с GitHub."
  else
    warn "Не удалось скачать заглушку с GitHub ($DECOY_SITE_URL) — использую минимальный запасной вариант."
    cat > /var/www/decoy-cdn/index.html <<'DECOYEOF'
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Service</title></head>
<body>Hello</body></html>
DECOYEOF
  fi
}

write_nginx_hardening() {
  # Shared SSL/gzip snippet — one place, included by every server block that needs it.
  mkdir -p /etc/nginx/snippets
  cat > /etc/nginx/snippets/ssl-params.conf <<'EOF'
ssl_protocols          TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 valid=60s;
resolver_timeout 2s;

gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_min_length 256;
gzip_types
    application/atom+xml application/geo+json application/javascript
    application/x-javascript application/json application/ld+json
    application/manifest+json application/rdf+xml application/rss+xml
    application/xhtml+xml application/xml application/wasm
    font/eot font/otf font/ttf image/svg+xml
    text/css text/javascript text/plain text/xml;
EOF

  # Any TLS connection with an SNI that doesn't match a configured server_name
  # gets the handshake dropped outright, instead of falling through to some
  # default vhost or error page — gives a port-scanner nothing to work with.
  cat > /etc/nginx/sites-available/00-reject-unknown-sni <<'EOF'
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    ssl_reject_handshake on;
}
EOF
  ln -sf /etc/nginx/sites-available/00-reject-unknown-sni /etc/nginx/sites-enabled/
}

issue_cert_for_domain() {
  local domain="$1"
  log "Проверяю DNS для $domain..."
  local resolved public_ip
  resolved=$(dig +short "$domain" A | tail -n1 || true)
  public_ip=$(curl -s -4 --max-time 5 https://api.ipify.org || true)
  if [[ -z "$resolved" ]]; then
    warn "$domain пока не резолвится. Certbot, скорее всего, не пройдёт, пока не создашь A-запись -> $public_ip"
  elif [[ "$resolved" != "$public_ip" ]]; then
    warn "$domain резолвится в $resolved, а не в IP этого сервера ($public_ip). Certbot может не пройти."
  fi

  if [[ ! -d "/etc/letsencrypt/live/$domain" ]]; then
    mkdir -p /var/www/certbot
    cat > "/etc/nginx/sites-available/$domain.bootstrap" <<EOF
server {
    listen 80;
    server_name $domain;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 404; }
}
EOF
    ln -sf "/etc/nginx/sites-available/$domain.bootstrap" "/etc/nginx/sites-enabled/$domain.bootstrap"
    nginx -t && systemctl reload nginx

    certbot certonly --webroot -w /var/www/certbot -d "$domain" --non-interactive --agree-tos \
      -m "admin@$domain" --no-eff-email || warn "Certbot не смог получить сертификат для $domain — поправь DNS и запусти certbot вручную позже"

    rm -f "/etc/nginx/sites-enabled/$domain.bootstrap" "/etc/nginx/sites-available/$domain.bootstrap"
  else
    log "Сертификат для $domain уже есть — пропускаю выпуск."
  fi
}

try_fetch_inbound_templates() {
  log "Проверяю репозиторий готовых шаблонов инбаундов..."
  local index
  index=$(curl -fsSL "$INBOUNDS_REPO_URL/index.json" 2>/dev/null || true)
  if [[ -z "$index" ]]; then
    warn "Репозиторий шаблонов пока пуст/не создан — эта функция появится позже."
    warn "Пока что настрой инбаунд вручную через UI панели."
    return 1
  fi
  echo "Доступные шаблоны:"
  echo "$index" | jq -r '.[] | "  - " + .name' 2>/dev/null || echo "$index"
  read -rp "Введи имя шаблона для скачивания (Enter — пропустить): " TEMPLATE_NAME
  [[ -z "$TEMPLATE_NAME" ]] && return 0
  if curl -fsSL "$INBOUNDS_REPO_URL/$TEMPLATE_NAME.json" -o "/tmp/inbound-$TEMPLATE_NAME.json"; then
    log "Шаблон сохранён: /tmp/inbound-$TEMPLATE_NAME.json (вставь его содержимое в UI панели при создании инбаунда)"
  else
    warn "Не удалось скачать шаблон $TEMPLATE_NAME"
  fi
}

write_list_nodes_script() {
  cat > /tmp/remnawave_list_nodes.py <<'LISTEOF'
#!/usr/bin/env python3
"""
Remnawave node lister — by qellyka
Fetches existing nodes from the panel and prints them as NUMBER|UUID|NAME|ADDRESS|CONNECTED
so a bash script can present a pick-by-number menu.
"""
import json
import os
import sys
import urllib.request
import urllib.error

PANEL_URL = os.environ.get("RW_PANEL_URL", "")
API_TOKEN = os.environ.get("RW_API_TOKEN", "")

if not all([PANEL_URL, API_TOKEN]):
    print("[ERROR] Missing RW_PANEL_URL / RW_API_TOKEN", file=sys.stderr)
    sys.exit(1)

req = urllib.request.Request(PANEL_URL.rstrip("/") + "/api/nodes", method="GET")
req.add_header("Authorization", f"Bearer {API_TOKEN}")
try:
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.loads(resp.read().decode())
except (urllib.error.URLError, urllib.error.HTTPError) as e:
    print(f"[ERROR] Could not fetch node list: {e}", file=sys.stderr)
    sys.exit(1)

nodes = data.get("response", [])
if not nodes:
    print("[ERROR] No nodes found in this panel", file=sys.stderr)
    sys.exit(2)

for i, n in enumerate(nodes, start=1):
    connected = "connected" if n.get("isConnected") else "disconnected"
    print(f"{i}|{n['uuid']}|{n.get('name','?')}|{n.get('address','?')}|{connected}")
LISTEOF
}

write_provision_script() {
  cat > /opt/remnanode/remnawave_provision.py <<'PYEOF'
#!/usr/bin/env python3
"""
Remnawave provisioning helper — by qellyka
Creates one Config Profile containing 1..4 selected inbound types, a Node referencing
them, and (optionally, only for the Reality+XHTTP inbound) a CDN-facing Host.
Uses the Remnawave v3.2.3 REST API directly, against a verified OpenAPI schema.
All parameters are passed via environment variables (avoids shell-quoting issues).
"""
import json
import os
import sys
import urllib.request
import urllib.error


def die(msg):
    print(f"[ERROR] {msg}", file=sys.stderr)
    sys.exit(1)


def env_bool(name, default=False):
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes")


def api(method, path, token, body=None):
    url = PANEL_URL.rstrip("/") + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode(errors="replace")
        die(f"{method} {path} -> HTTP {e.code}: {body_text}")
    except urllib.error.URLError as e:
        die(f"{method} {path} -> connection failed: {e}")


PANEL_URL = os.environ.get("RW_PANEL_URL", "")
API_TOKEN = os.environ.get("RW_API_TOKEN", "")
NODE_NAME = os.environ.get("RW_NODE_NAME", "node-1")
NODE_ADDRESS = os.environ.get("RW_NODE_ADDRESS", "")
NODE_PORT = int(os.environ.get("RW_NODE_PORT", "3000"))

EXISTING_NODE_UUID_CHECK = os.environ.get("RW_EXISTING_NODE_UUID", "").strip()
if not all([PANEL_URL, API_TOKEN]):
    die("Missing required env vars: RW_PANEL_URL, RW_API_TOKEN")
if not EXISTING_NODE_UUID_CHECK and not NODE_ADDRESS:
    die("Missing RW_NODE_ADDRESS (required when creating a new node; not needed when RW_EXISTING_NODE_UUID is set)")

inbounds = []

# ---- Reality + TCP (raw) ----
if env_bool("RW_ENABLE_REALITY_TCP"):
    tag = "reality-tcp"
    inbounds.append({
        "tag": tag,
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_REALITY_TCP_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
                "show": False, "xver": 0,
                "target": f"{os.environ['RW_REALITY_TCP_SNI']}:443",
                "serverNames": [os.environ["RW_REALITY_TCP_SNI"]],
                "privateKey": os.environ["RW_REALITY_TCP_PRIVATE_KEY"],
                "shortIds": [os.environ["RW_REALITY_TCP_SHORTID"]]
            }
        }
    })

# ---- Reality + gRPC ----
if env_bool("RW_ENABLE_REALITY_GRPC"):
    tag = "reality-grpc"
    inbounds.append({
        "tag": tag,
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_REALITY_GRPC_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "grpc",
            "security": "reality",
            "grpcSettings": {"serviceName": os.environ["RW_REALITY_GRPC_SERVICE_NAME"], "multiMode": False},
            "realitySettings": {
                "show": False, "xver": 0,
                "target": f"{os.environ['RW_REALITY_GRPC_SNI']}:443",
                "serverNames": [os.environ["RW_REALITY_GRPC_SNI"]],
                "privateKey": os.environ["RW_REALITY_GRPC_PRIVATE_KEY"],
                "shortIds": [os.environ["RW_REALITY_GRPC_SHORTID"]]
            }
        }
    })

# ---- Reality + XHTTP (raw, direct connection — NOT CDN-compatible) ----
if env_bool("RW_ENABLE_REALITY_XHTTP"):
    tag = "reality-xhttp"
    inbounds.append({
        "tag": tag,
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_REALITY_XHTTP_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "xhttp",
            "security": "reality",
            "realitySettings": {
                "show": False, "xver": 0,
                "target": f"{os.environ['RW_REALITY_XHTTP_SNI']}:443",
                "serverNames": [os.environ["RW_REALITY_XHTTP_SNI"]],
                "privateKey": os.environ["RW_REALITY_XHTTP_PRIVATE_KEY"],
                "shortIds": [os.environ["RW_REALITY_XHTTP_SHORTID"]]
            },
            "xhttpSettings": {
                "path": os.environ["RW_REALITY_XHTTP_PATH"],
                "mode": "auto",
                "xPaddingBytes": "100-1000"
            }
        }
    })

# ---- TLS + XHTTP through CDN (separate inbound, plain TLS — never Reality; the
# whole point is bypassing mobile-carrier SNI whitelisting via a CDN edge) ----
cdn_xhttp_tag = None
if env_bool("RW_ENABLE_CDN_XHTTP"):
    cdn_xhttp_tag = "cdn-xhttp"
    cdn_cert_pem = os.environ.get("RW_CDN_XHTTP_CERT_PEM", "")
    cdn_key_pem = os.environ.get("RW_CDN_XHTTP_KEY_PEM", "")
    if cdn_cert_pem and cdn_key_pem:
        # No filesystem access / no local Nginx on the node — Xray terminates TLS
        # itself, with the cert embedded inline. The Yandex CDN resource's "Origin
        # protocol" must be set to HTTPS to match (not the Nginx+externalProxy pattern).
        security_block = {
            "security": "tls",
            "tlsSettings": {
                "certificates": [{
                    "certificate": cdn_cert_pem.splitlines(),
                    "key": cdn_key_pem.splitlines()
                }],
                "alpn": ["h2", "http/1.1"]
            }
        }
        listen_addr = "0.0.0.0"
    else:
        # Server-access case: Nginx terminates real TLS locally, Xray sits behind
        # it on loopback with security:none (externalProxy in the Host tells the
        # panel the public-facing connection is TLS).
        security_block = {"security": "none"}
        listen_addr = "127.0.0.1"
    inbounds.append({
        "tag": cdn_xhttp_tag,
        "listen": listen_addr,
        "port": int(os.environ["RW_CDN_XHTTP_PORT"]),
        "protocol": "vless",
        "settings": {"clients": [], "decryption": "none"},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "xhttp",
            **security_block,
            "xhttpSettings": {
                "path": os.environ["RW_CDN_XHTTP_PATH"],
                "mode": "packet-up",
                "xPaddingBytes": "100-1000",
                "xPaddingObfsMode": True,
                "xPaddingKey": "hash",
                "xPaddingHeader": "X-Client-Version",
                "xPaddingPlacement": "queryInHeader",
                "xPaddingMethod": "tokenish",
                "uplinkHTTPMethod": "GET",
                "uplinkDataPlacement": "body",
                "scMaxEachPostBytes": "500000-1000000",
                "scMinPostsIntervalMs": "50-150",
                "scStreamUpServerSecs": "60-180",
                "uplinkChunkSize": 131072,
                "enableXmux": True,
                "xmux": {
                    "maxConcurrency": "16-32", "maxConnections": 0,
                    "cMaxReuseTimes": 1000, "hMaxRequestTimes": "600-900",
                    "hMaxReusableSecs": "100", "hKeepAlivePeriod": 20000
                }
            }
        }
    })

# ---- Hysteria2 ----
if env_bool("RW_ENABLE_HY2"):
    tag = "hysteria2"
    hy2_cert_pem = os.environ.get("RW_HY2_CERT_PEM", "")
    hy2_key_pem = os.environ.get("RW_HY2_KEY_PEM", "")
    if hy2_cert_pem and hy2_key_pem:
        # No filesystem access to the node itself — embed the PEM content directly
        # in the config (one array element per line), instead of referencing a path.
        cert_block = {
            "certificate": hy2_cert_pem.splitlines(),
            "key": hy2_key_pem.splitlines()
        }
    else:
        cert_block = {
            "certificateFile": os.environ["RW_HY2_CERT_FILE"],
            "keyFile": os.environ["RW_HY2_KEY_FILE"]
        }
    inbounds.append({
        "tag": tag,
        "listen": "0.0.0.0",
        "port": int(os.environ["RW_HY2_PORT"]),
        "protocol": "hysteria",
        "settings": {"version": 2, "clients": []},
        "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
        "streamSettings": {
            "network": "hysteria",
            "security": "tls",
            "tlsSettings": {
                "alpn": ["h3"], "minVersion": "1.3", "maxVersion": "1.3",
                "certificates": [cert_block]
            },
            "hysteriaSettings": {
                "version": 2, "udpIdleTimeout": 60,
                "masquerade": {"type": "proxy", "url": os.environ.get("RW_HY2_MASQUERADE_URL", "https://www.bing.com"), "rewriteHost": True}
            }
        }
    })

if not inbounds:
    die("No inbounds selected — nothing to provision. (This shouldn't happen if the bash script's logic is correct.)")

print(f"[1/4] Verifying API token... ({len(inbounds)} inbound(s) to create)")
api("GET", "/api/hosts", API_TOKEN)
print("      OK, token is valid.")

print("[2/4] Creating Config Profile...")
profile_body = {
    "name": f"profile-{NODE_NAME}",
    "config": {
        "inbounds": inbounds,
        "outbounds": [{"protocol": "freedom", "tag": "direct"}]
    }
}
profile_resp = api("POST", "/api/config-profiles", API_TOKEN, profile_body)["response"]
profile_uuid = profile_resp["uuid"]
tag_to_uuid = {i["tag"]: i["uuid"] for i in profile_resp["inbounds"]}
missing = [i["tag"] for i in inbounds if i["tag"] not in tag_to_uuid]
if missing:
    die(f"Created profile but couldn't find inbound(s) with tag(s)={missing} in response")
print(f"      Profile UUID: {profile_uuid}")
for t, u in tag_to_uuid.items():
    print(f"      Inbound '{t}' UUID: {u}")

print("[3/4] Creating/updating Node...")
EXISTING_NODE_UUID = os.environ.get("RW_EXISTING_NODE_UUID", "").strip()
if EXISTING_NODE_UUID:
    node_body = {
        "uuid": EXISTING_NODE_UUID,
        "configProfile": {
            "activeConfigProfileUuid": profile_uuid,
            "activeInbounds": list(tag_to_uuid.values())
        }
    }
    node_resp = api("PATCH", "/api/nodes", API_TOKEN, node_body)["response"]
    node_uuid = node_resp["uuid"]
    print(f"      Updated EXISTING node: {node_uuid}")
    print("      (This replaced whatever config profile/inbounds it had before —")
    print("       if it had other manually-configured inbounds, re-add them via UI.)")
else:
    node_body = {
        "name": NODE_NAME,
        "address": NODE_ADDRESS,
        "port": NODE_PORT,
        "configProfile": {
            "activeConfigProfileUuid": profile_uuid,
            "activeInbounds": list(tag_to_uuid.values())
        }
    }
    node_resp = api("POST", "/api/nodes", API_TOKEN, node_body)["response"]
    node_uuid = node_resp["uuid"]
    print(f"      Created new Node: {node_uuid}")
    print("      NOTE: SECRET_KEY for this node is not exposed via this API — copy it")
    print("      from the panel UI (Nodes -> this node -> Important information).")

host_uuid = None
if cdn_xhttp_tag:
    print("[4/4] Creating Host (CDN entry point for cdn-xhttp inbound)...")
    cdn_domain = os.environ["RW_CDN_DOMAIN"]
    host_body = {
        "inbound": {"configProfileUuid": profile_uuid, "configProfileInboundUuid": tag_to_uuid[cdn_xhttp_tag]},
        "remark": f"CDN — {cdn_domain}",
        "address": cdn_domain,
        "port": 443,
        "path": os.environ["RW_CDN_XHTTP_PATH"],
        "sni": cdn_domain,
        "alpn": "h2,http/1.1",
        "fingerprint": "chrome",
        "securityLayer": "NONE",
        "xhttpExtraParams": {
            "uplinkDataPlacement": "body",
            "uplinkChunkSize": 131072,
            "scMaxEachPostBytes": "500000-1000000",
            "scMinPostsIntervalMs": "50-150",
            "scStreamUpServerSecs": "60-180",
            "xPaddingBytes": "100-1000",
            "xPaddingObfsMode": True,
            "xPaddingKey": "hash",
            "xPaddingHeader": "X-Client-Version",
            "xPaddingPlacement": "queryInHeader",
            "xPaddingMethod": "tokenish"
        }
    }
    host_resp = api("POST", "/api/hosts", API_TOKEN, host_body)["response"]
    host_uuid = host_resp["uuid"]
    print("      Reading the created Host back for verification:")
    print(json.dumps(api("GET", f"/api/hosts/{host_uuid}", API_TOKEN), indent=2))
else:
    print("[4/4] No CDN inbound selected — skipping Host creation.")
    print("      (Reality-based/Hysteria2 inbounds are reached directly by IP:port,")
    print("       no Host object is required for them to work.)")

print()
print("=====================================================")
print(f"Done. Profile: {profile_uuid}  Node: {node_uuid}", end="")
print(f"  Host: {host_uuid}" if host_uuid else "")
print("PLEASE open the panel UI and visually confirm everything looks correct")
print("before relying on it for real traffic.")
print("=====================================================")
PYEOF
}

write_bootstrap_script() {
  cat > /opt/remnawave/remnawave_bootstrap.py <<'PYEOF'
#!/usr/bin/env python3
"""
Remnawave panel bootstrap — by qellyka
Registers the first admin account (only works if no admin exists yet).

API-token creation was intentionally NOT automated here: creating a token
via the API immediately after an API-based registration consistently
returns 403 in practice, even though creating one through the panel UI
with the same freshly-registered account works fine. Root cause unclear —
rather than keep guessing against a live install, the token is created by
hand in the UI and handed back to the deploy script.
"""
import json
import os
import sys
import time
import urllib.request
import urllib.error

PANEL_URL = os.environ.get("RW_PANEL_URL", "")
ADMIN_USERNAME = os.environ.get("RW_ADMIN_USERNAME", "")
ADMIN_PASSWORD = os.environ.get("RW_ADMIN_PASSWORD", "")

if not all([PANEL_URL, ADMIN_USERNAME, ADMIN_PASSWORD]):
    print("[ERROR] Missing RW_PANEL_URL / RW_ADMIN_USERNAME / RW_ADMIN_PASSWORD", file=sys.stderr)
    sys.exit(1)


def call(method, path, token=None, body=None):
    url = PANEL_URL.rstrip("/") + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode())


status = None
for attempt in range(15):
    try:
        status = call("GET", "/api/auth/status")
        break
    except (urllib.error.URLError, urllib.error.HTTPError):
        time.sleep(2)
if status is None:
    print("[ERROR] Panel did not become reachable in time", file=sys.stderr)
    sys.exit(1)

if not status["response"]["isRegisterAllowed"]:
    print("[SKIP] Registration is not open (an admin already exists).", file=sys.stderr)
    sys.exit(2)

call("POST", "/api/auth/register", body={"username": ADMIN_USERNAME, "password": ADMIN_PASSWORD})
print(f"ADMIN_USERNAME={ADMIN_USERNAME}")
PYEOF
}

#################################
# PANEL MODE (interactive)
#################################
install_panel() {
  echo "Перед этим шагом нужны две A-записи в DNS, указывающие на IP этого сервера:"
  echo "  - домен для панели (например panel.example.com)"
  echo "  - домен для страницы подписки (например sub.example.com)"
  echo "Если уже создал — просто продолжай, ничего страшного, если ещё нет — сделай это"
  echo "в панели DNS у регистратора прямо сейчас (займёт минуту), потом возвращайся."
  echo "Скрипт сам проверит, резолвятся ли они правильно, перед выпуском сертификатов."
  echo ""
  read_domain "Домен для панели администратора (например panel.example.com): " PANEL_DOMAIN
  read_domain "Домен для страницы подписки (например sub.example.com): " SUB_DOMAIN
  read -rp "Порт SSH, который нельзя закрывать [22]: " SSH_PORT
  SSH_PORT=${SSH_PORT:-22}
  [[ -n "$PANEL_DOMAIN" && -n "$SUB_DOMAIN" ]] || die "Оба домена обязательны"
  echo ""

  install_base
  apt install -y -qq nginx certbot

  mkdir -p /opt/remnawave
  cd /opt/remnawave

  if [[ -f .env && -f docker-compose.yml ]]; then
    log ".env уже существует — повторный запуск, секреты не трогаю (иначе пароль Postgres"
    log "разойдётся с уже инициализированной базой, и панель уйдёт в цикл рестартов)."
    PG_PW=$(grep "^POSTGRES_PASSWORD=" .env | cut -d= -f2-)
    grep -q "^FRONT_END_DOMAIN=" .env && sed -i "s/^FRONT_END_DOMAIN=.*/FRONT_END_DOMAIN=$PANEL_DOMAIN/" .env
    grep -q "^SUB_PUBLIC_DOMAIN=" .env && sed -i "s/^SUB_PUBLIC_DOMAIN=.*/SUB_PUBLIC_DOMAIN=$SUB_DOMAIN/" .env
  else
    log "Скачиваю официальные шаблоны docker-compose и .env..."
    curl -fsSL -o docker-compose.yml https://raw.githubusercontent.com/remnawave/backend/refs/heads/main/docker-compose-prod.yml
    curl -fsSL -o .env https://raw.githubusercontent.com/remnawave/backend/refs/heads/main/.env.sample

    log "Генерирую секреты..."
    sed -i "s/^APP_SECRET=.*/APP_SECRET=$(openssl rand -hex 64)/" .env
    sed -i "s/^JWT_AUTH_SECRET=.*/JWT_AUTH_SECRET=$(openssl rand -hex 64)/" .env
    sed -i "s/^JWT_API_TOKENS_SECRET=.*/JWT_API_TOKENS_SECRET=$(openssl rand -hex 64)/" .env
    sed -i "s/^METRICS_PASS=.*/METRICS_PASS=$(openssl rand -hex 64)/" .env
    sed -i "s/^WEBHOOK_SECRET_HEADER=.*/WEBHOOK_SECRET_HEADER=$(openssl rand -hex 64)/" .env
    PG_PW=$(openssl rand -hex 24)
    sed -i "s/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$PG_PW/" .env
    sed -i "s|^\(DATABASE_URL=\"postgresql://postgres:\)[^@]*\(@.*\)|\1$PG_PW\2|" .env
    grep -q "^FRONT_END_DOMAIN=" .env && sed -i "s/^FRONT_END_DOMAIN=.*/FRONT_END_DOMAIN=$PANEL_DOMAIN/" .env
    grep -q "^SUB_PUBLIC_DOMAIN=" .env && sed -i "s/^SUB_PUBLIC_DOMAIN=.*/SUB_PUBLIC_DOMAIN=$SUB_DOMAIN/" .env
  fi

  log "Запускаю контейнеры панели..."
  docker compose up -d

  issue_cert_for_domain "$PANEL_DOMAIN"
  issue_cert_for_domain "$SUB_DOMAIN"

  write_nginx_hardening

  log "Пишу конфиги Nginx..."
  cat > /etc/nginx/sites-available/remnawave-panel <<EOF
server {
    listen 80; server_name $PANEL_DOMAIN;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl; http2 on; server_name $PANEL_DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$PANEL_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$PANEL_DOMAIN/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
EOF

  cat > /etc/nginx/sites-available/remnawave-sub <<EOF
server {
    listen 80; server_name $SUB_DOMAIN;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl; http2 on; server_name $SUB_DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$SUB_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$SUB_DOMAIN/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    location / {
        proxy_pass http://127.0.0.1:3010;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF
  ln -sf /etc/nginx/sites-available/remnawave-panel /etc/nginx/sites-enabled/
  ln -sf /etc/nginx/sites-available/remnawave-sub /etc/nginx/sites-enabled/
  rm -f /etc/nginx/sites-enabled/default
  nginx -t && systemctl reload nginx

  EXTRA_INPUT_RULES="        tcp dport { 80, 443 } accept"
  write_nftables_base

  echo ""
  echo "Создать первого администратора автоматически, прямо сейчас?"
  echo "  1) Да (работает только для только что установленной, ещё пустой панели)"
  echo "  2) Нет — сделаю сам в UI позже (страницу подписки придётся донастроить вручную)"
  read -rp "Введите номер [1-2]: " BOOTSTRAP_CHOICE
  BOOTSTRAP_OK=false
  ADMIN_CREATED=false
  if [[ "$BOOTSTRAP_CHOICE" == "1" ]]; then
    read -rp "Логин администратора: " RW_ADMIN_USERNAME
    RW_ADMIN_PASSWORD=$(openssl rand -base64 18)
    apt install -y -qq python3
    write_bootstrap_script
    BOOTSTRAP_OUT=$(RW_PANEL_URL="https://$PANEL_DOMAIN" RW_ADMIN_USERNAME="$RW_ADMIN_USERNAME" RW_ADMIN_PASSWORD="$RW_ADMIN_PASSWORD" \
      python3 /opt/remnawave/remnawave_bootstrap.py 2>&1)
    echo "$BOOTSTRAP_OUT" | grep -q "^ADMIN_USERNAME=" && ADMIN_CREATED=true

    if [[ "$ADMIN_CREATED" == true ]]; then
      echo "ADMIN_USERNAME=$RW_ADMIN_USERNAME" > /opt/remnawave/bootstrap-credentials.txt
      echo "ADMIN_PASSWORD=$RW_ADMIN_PASSWORD" >> /opt/remnawave/bootstrap-credentials.txt
      chmod 600 /opt/remnawave/bootstrap-credentials.txt

      echo ""
      log "Администратор создан:"
      echo "  Логин:  $RW_ADMIN_USERNAME"
      echo "  Пароль: $RW_ADMIN_PASSWORD"
      echo "(сохранено в /opt/remnawave/bootstrap-credentials.txt, chmod 600)"
      echo ""
      echo "Создание токена через API у нас пока не работает надёжно (стабильно"
      echo "получаем 403 сразу после регистрации, хотя через UI создаётся без проблем)."
      echo "Зайди в панель — https://$PANEL_DOMAIN — под этими данными,"
      echo "создай токен: Settings -> API Tokens -> Create, и вставь его сюда."
      echo "(Enter без значения — пропустить, донастроишь подписку вручную позже)"
      read -rp "API-токен: " API_TOKEN_VALUE
      if [[ -n "$API_TOKEN_VALUE" ]]; then
        HTTP_CODE=$(curl -fsS -o /dev/null -w "%{http_code}" \
          -H "Authorization: Bearer $API_TOKEN_VALUE" "https://$PANEL_DOMAIN/api/hosts" || true)
        if [[ "$HTTP_CODE" == "200" ]]; then
          BOOTSTRAP_OK=true
          log "Токен подтверждён."
        else
          warn "Токен не прошёл проверку (код ответа: $HTTP_CODE) — возможно, опечатка при вставке."
          warn "Страница подписки не получит REMNAWAVE_API_TOKEN автоматически."
        fi
      fi
    else
      warn "Автосоздание администратора не удалось (см. вывод ниже) — создай его вручную через UI."
      echo "$BOOTSTRAP_OUT"
    fi
  fi

  log "Разворачиваю сервер подписки..."
  mkdir -p /opt/remnawave/subscription
  cat > /opt/remnawave/subscription/docker-compose.yml <<'EOF'
services:
  remnawave-subscription-page:
    image: remnawave/subscription-page:latest
    container_name: remnawave-subscription-page
    hostname: remnawave-subscription-page
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:3010:3010'
    networks:
      - remnawave-network
networks:
  remnawave-network:
    external: true
EOF
  cat > /opt/remnawave/subscription/.env <<EOF
APP_PORT=3010
REMNAWAVE_PANEL_URL=http://remnawave:3000
REMNAWAVE_API_TOKEN=${API_TOKEN_VALUE:-}
CUSTOM_SUB_PREFIX=
MARZBAN_LEGACY_LINK_ENABLED=false
MARZBAN_LEGACY_SECRET_KEY=
TRUST_PROXY=1
EOF
  if [[ "$BOOTSTRAP_OK" != true ]]; then
    warn "REMNAWAVE_API_TOKEN оставлен пустым в /opt/remnawave/subscription/.env"
    warn "Создай токен вручную (Settings -> API Tokens), впиши его туда, затем:"
    warn "  cd /opt/remnawave/subscription && docker compose up -d"
  fi
  cd /opt/remnawave/subscription
  docker compose up -d
  cd /opt/remnawave


  echo ""
  echo "==================================================="
  log "Панель установлена."
  echo "==================================================="
  echo "Панель:        https://$PANEL_DOMAIN"
  echo "Подписка:      https://$SUB_DOMAIN"
  echo "Пароль Postgres (также в /opt/remnawave/.env): $PG_PW"
  if [[ "$BOOTSTRAP_OK" == true ]]; then
    echo ""
    echo "Администратор создан, токен подтверждён и передан странице подписки:"
    echo "  Логин:  $RW_ADMIN_USERNAME"
    echo "  Пароль: $RW_ADMIN_PASSWORD"
    echo "  API-токен: $API_TOKEN_VALUE"
    echo "(сохранено в /opt/remnawave/bootstrap-credentials.txt, chmod 600)"
    echo ""
    echo "Можешь сразу запускать этот же скрипт в режиме ноды и вставить"
    echo "этот URL панели + этот API-токен при автопровижининге."
  elif [[ "$ADMIN_CREATED" == true ]]; then
    echo ""
    warn "Администратор создан, но токен не был передан (пропущен или не прошёл проверку)."
    echo "  Логин:  $RW_ADMIN_USERNAME"
    echo "  Пароль: $RW_ADMIN_PASSWORD"
    echo "(сохранено в /opt/remnawave/bootstrap-credentials.txt, chmod 600)"
    echo "Создай токен в панели (Settings -> API Tokens -> Create), впиши в"
    echo "/opt/remnawave/subscription/.env и перезапусти: docker compose up -d"
  else
    echo ""
    echo "Дальше: зайди в панель, создай админа, потом"
    echo "Settings -> API Tokens, чтобы получить токен для режима ноды."
  fi
  echo "==================================================="
}

install_node() {
  if [[ "${EXISTING_NODE:-false}" == true ]]; then
    echo "Применяем инбаунды к уже существующей, подключённой ноде."
    echo "Нужен API-токен панели — если ещё не создавал, зайди в панель:"
    echo "  Settings -> API Tokens -> Create, скопируй значение, потом вернись сюда."
    echo "Если токен уже есть — просто вставь его."
    echo ""
    read -rp "URL панели (например https://panel.example.com): " RW_PANEL_URL
    read -rp "API-токен: " RW_API_TOKEN
    [[ -n "$RW_PANEL_URL" && -n "$RW_API_TOKEN" ]] || die "URL панели и API-токен обязательны"
    echo ""

    apt-get update -qq >/dev/null 2>&1 || true
    apt-get install -y -qq python3 jq curl >/dev/null 2>&1
    write_list_nodes_script

    log "Получаю список нод из панели..."
    NODES_LIST=$(RW_PANEL_URL="$RW_PANEL_URL" RW_API_TOKEN="$RW_API_TOKEN" python3 /tmp/remnawave_list_nodes.py) \
      || die "Не удалось получить список нод — проверь URL панели и токен"

    echo ""
    echo "Доступные ноды:"
    echo "$NODES_LIST" | awk -F'|' '{printf "  %s) %s  [%s]  %s\n", $1, $3, $5, $4}'
    echo ""
    read -rp "Выбери номер ноды: " NODE_PICK
    PICKED_LINE=$(echo "$NODES_LIST" | awk -F'|' -v n="$NODE_PICK" '$1==n')
    [[ -n "$PICKED_LINE" ]] || die "Некорректный выбор"
    RW_EXISTING_NODE_UUID=$(echo "$PICKED_LINE" | cut -d'|' -f2)
    log "Выбрана нода: $(echo "$PICKED_LINE" | cut -d'|' -f3) ($RW_EXISTING_NODE_UUID)"
    echo ""

    echo "Что установить на эту ноду?"
    echo "  1) Установить 4 базовых инбаунда (Reality+TCP, Reality+gRPC, Reality+XHTTP, Hysteria2)"
    echo "  2) Настроить связку с CDN (TLS+XHTTP через CDN, обход белых списков)"
    echo "  3) Всё сразу — варианты 1 и 2 вместе"
    read -rp "Введите номер [1-3]: " NODE_SETUP_CHOICE
    [[ "$NODE_SETUP_CHOICE" =~ ^[1-3]$ ]] || die "Некорректный выбор"
    # remap onto the same internal numbering the rest of this function expects (2/3/4)
    case "$NODE_SETUP_CHOICE" in
      1) NODE_SETUP_CHOICE=2 ;;
      2) NODE_SETUP_CHOICE=3 ;;
      3) NODE_SETUP_CHOICE=4 ;;
    esac
    echo ""
  else
    echo "Что делаем с этой нодой?"
    echo "  1) Просто подключить ноду (SECRET_KEY уже есть на руках)"
    echo "  2) Установить 4 базовых инбаунда (Reality+TCP, Reality+gRPC, Reality+XHTTP, Hysteria2)"
    echo "  3) Настроить связку с CDN (TLS+XHTTP через CDN, обход белых списков)"
    echo "  4) Всё сразу — варианты 2 и 3 вместе"
    read -rp "Введите номер [1-4]: " NODE_SETUP_CHOICE
    [[ "$NODE_SETUP_CHOICE" =~ ^[1-4]$ ]] || die "Некорректный выбор"
    echo ""
  fi

  if [[ "${EXISTING_NODE:-false}" != true ]]; then
    read -rp "IP панели, для ограничения доступа к ноде (Enter — пропустить, менее безопасно): " PANEL_IP
    read -rp "NODE_PORT [3000]: " NODE_PORT; NODE_PORT=${NODE_PORT:-3000}
    read -rp "XTLS_API_PORT [61000]: " XTLS_API_PORT; XTLS_API_PORT=${XTLS_API_PORT:-61000}
    read -rp "Порт SSH, который нельзя закрывать [22]: " SSH_PORT; SSH_PORT=${SSH_PORT:-22}
    echo ""

    echo "Блокировать входящий ICMP (ping) на этой ноде?"
    echo "  1) Да (рекомендуется — обычные клиентские IP не отвечают на пинг)"
    echo "  2) Нет"
    read -rp "Введите номер [1-2]: " ICMP_CHOICE
    BLOCK_ICMP=false; [[ "$ICMP_CHOICE" == "1" ]] && BLOCK_ICMP=true
    echo ""
  fi

  ENABLE_REALITY_TCP=false; ENABLE_REALITY_GRPC=false; ENABLE_REALITY_XHTTP=false; ENABLE_HY2=false; ENABLE_CDN_XHTTP=false
  AUTO_PROVISION=false
  SECRET_SOURCE="1"

  case "$NODE_SETUP_CHOICE" in
    2|4)
      ENABLE_REALITY_TCP=true; ENABLE_REALITY_GRPC=true; ENABLE_REALITY_XHTTP=true; ENABLE_HY2=true
      ;;
  esac
  case "$NODE_SETUP_CHOICE" in
    3|4)
      ENABLE_CDN_XHTTP=true
      ;;
  esac
  [[ "$NODE_SETUP_CHOICE" != "1" ]] && { AUTO_PROVISION=true; SECRET_SOURCE="2"; }

  if [[ "$SECRET_SOURCE" == "1" && "${EXISTING_NODE:-false}" != true ]]; then
    read -rp "SECRET_KEY из панели (Ноды -> эта нода -> Важная информация): " SECRET_KEY
    [[ -n "$SECRET_KEY" ]] || die "SECRET_KEY обязателен"
  fi

  # Базовые пресеты — фиксированные разумные значения, без лишних вопросов
  if [[ "$ENABLE_REALITY_TCP" == true ]]; then
    REALITY_TCP_PORT=443
    REALITY_TCP_SNI="yandex.ru"
  fi
  if [[ "$ENABLE_REALITY_GRPC" == true ]]; then
    REALITY_GRPC_PORT=8443
    REALITY_GRPC_SNI="yandex.ru"
    REALITY_GRPC_SERVICE_NAME=$(openssl rand -hex 6)
  fi
  if [[ "$ENABLE_REALITY_XHTTP" == true ]]; then
    REALITY_XHTTP_PORT=2053
    REALITY_XHTTP_SNI="yandex.ru"
    REALITY_XHTTP_PATH="/$(openssl rand -hex 8)/"
  fi
  if [[ "$ENABLE_HY2" == true ]]; then
    HY2_PORT=8444
  fi
  if [[ "$ENABLE_CDN_XHTTP" == true ]]; then
    echo "Для CDN-инбаунда нужны две вещи, которые скрипт сам не сделает:"
    echo "  1) A-запись домена-origin на IP этого сервера (не требует доступа к серверу,"
    echo "     только к панели DNS у регистратора) — если уже сделал, просто продолжай"
    echo "  2) CDN-ресурс в консоли провайдера (Yandex Cloud CDN или другой), созданный"
    echo "     ПОСЛЕ этого шага — сертификат origin будет готов только к концу скрипта,"
    echo "     так что создавать ресурс раньше смысла нет, к этому вернёмся в конце"
    echo ""
    read_domain "Домен origin для этой ноды (dest/CDN-источник, например origin1.example.com): " NODE_ORIGIN_DOMAIN
    read_domain "Публичный домен CDN-ресурса (например cdn.example.com): " CDN_PUBLIC_DOMAIN
    if [[ "${EXISTING_NODE:-false}" == true ]]; then
      # No Nginx in front — Xray's own port IS the public one CDN connects to.
      # Not 443: that's already the Reality+TCP default and would collide if both
      # are enabled together. Yandex CDN lets you specify a custom origin port —
      # check "Порт" in the origin settings if 9443 doesn't suit you.
      CDN_XHTTP_LOCAL_PORT=9443
    else
      CDN_XHTTP_LOCAL_PORT=20000
    fi
    CDN_XHTTP_PATH="/$(openssl rand -hex 8)/"
  fi
  echo ""

  if [[ "$AUTO_PROVISION" == true && "${EXISTING_NODE:-false}" != true ]]; then
    echo "Нужен API-токен панели — если ещё не создавал, зайди в панель:"
    echo "  Settings -> API Tokens -> Create, скопируй значение, потом вернись сюда."
    echo ""
    read -rp "URL панели (например https://panel.example.com): " RW_PANEL_URL
    read -rp "API-токен: " RW_API_TOKEN
    read -rp "Публичный IP/адрес ЭТОЙ ноды (то, что панель будет использовать для подключения): " RW_NODE_ADDRESS
    [[ -n "$RW_PANEL_URL" && -n "$RW_API_TOKEN" && -n "$RW_NODE_ADDRESS" ]] || die "Все три поля обязательны для автопровижининга"
  fi

  if [[ "$AUTO_PROVISION" != true ]]; then
    echo ""
    echo "Установить готовые шаблоны инбаундов из репозитория?"
    echo "  1) Да"
    echo "  2) Нет"
    read -rp "Введите номер [1-2]: " INBOUNDS_CHOICE
  fi
  echo ""

  if [[ "${EXISTING_NODE:-false}" == true ]]; then
    apt-get update -qq >/dev/null 2>&1 || true
    apt-get install -y -qq curl openssl jq >/dev/null 2>&1
  else
    install_base
  fi

  if [[ "$ENABLE_REALITY_TCP" == true ]]; then
    generate_reality_keys
    REALITY_TCP_PRIVATE_KEY="$REALITY_PRIVATE_KEY"; REALITY_TCP_PUBLIC_KEY="$REALITY_PUBLIC_KEY"; REALITY_TCP_SHORTID="$REALITY_SHORTID"
  fi
  if [[ "$ENABLE_REALITY_GRPC" == true ]]; then
    generate_reality_keys
    REALITY_GRPC_PRIVATE_KEY="$REALITY_PRIVATE_KEY"; REALITY_GRPC_PUBLIC_KEY="$REALITY_PUBLIC_KEY"; REALITY_GRPC_SHORTID="$REALITY_SHORTID"
  fi
  if [[ "$ENABLE_REALITY_XHTTP" == true ]]; then
    generate_reality_keys
    REALITY_XHTTP_PRIVATE_KEY="$REALITY_PRIVATE_KEY"; REALITY_XHTTP_PUBLIC_KEY="$REALITY_PUBLIC_KEY"; REALITY_XHTTP_SHORTID="$REALITY_SHORTID"
  fi
  if [[ "$ENABLE_HY2" == true ]]; then
    generate_hy2_cert
    if [[ "${EXISTING_NODE:-false}" == true ]]; then
      # No filesystem access to the node itself — pass PEM content inline instead of a path.
      HY2_CERT_PEM=$(cat /etc/xray-certs/hy2-cert.crt)
      HY2_KEY_PEM=$(cat /etc/xray-certs/hy2-key.pem)
    fi
  fi
  if [[ "$ENABLE_CDN_XHTTP" == true && "${EXISTING_NODE:-false}" == true ]]; then
    # No Nginx/certbot possible without server access — Xray terminates TLS itself.
    # Self-signed by default; replace /etc/xray-certs/hy2-cert.crt with a real cert
    # (e.g. exported from Yandex Certificate Manager) before running this if you want one.
    generate_hy2_cert
    CDN_XHTTP_CERT_PEM=$(cat /etc/xray-certs/hy2-cert.crt)
    CDN_XHTTP_KEY_PEM=$(cat /etc/xray-certs/hy2-key.pem)
  fi

  if [[ "$AUTO_PROVISION" == true ]]; then
    log "Запускаю автоматический провижининг через API панели..."
    mkdir -p /opt/remnanode
    apt-get install -y -qq python3 >/dev/null 2>&1
    write_provision_script

    env \
      RW_PANEL_URL="$RW_PANEL_URL" RW_API_TOKEN="$RW_API_TOKEN" \
      RW_NODE_NAME="node-$(hostname)" RW_NODE_ADDRESS="${RW_NODE_ADDRESS:-}" RW_NODE_PORT="${NODE_PORT:-3000}" \
      RW_EXISTING_NODE_UUID="${RW_EXISTING_NODE_UUID:-}" \
      RW_ENABLE_REALITY_TCP="$ENABLE_REALITY_TCP" RW_REALITY_TCP_PORT="${REALITY_TCP_PORT:-}" \
      RW_REALITY_TCP_SNI="${REALITY_TCP_SNI:-}" RW_REALITY_TCP_PRIVATE_KEY="${REALITY_TCP_PRIVATE_KEY:-}" \
      RW_REALITY_TCP_SHORTID="${REALITY_TCP_SHORTID:-}" \
      RW_ENABLE_REALITY_GRPC="$ENABLE_REALITY_GRPC" RW_REALITY_GRPC_PORT="${REALITY_GRPC_PORT:-}" \
      RW_REALITY_GRPC_SNI="${REALITY_GRPC_SNI:-}" RW_REALITY_GRPC_PRIVATE_KEY="${REALITY_GRPC_PRIVATE_KEY:-}" \
      RW_REALITY_GRPC_SHORTID="${REALITY_GRPC_SHORTID:-}" RW_REALITY_GRPC_SERVICE_NAME="${REALITY_GRPC_SERVICE_NAME:-}" \
      RW_ENABLE_REALITY_XHTTP="$ENABLE_REALITY_XHTTP" RW_REALITY_XHTTP_PORT="${REALITY_XHTTP_PORT:-}" \
      RW_REALITY_XHTTP_PATH="${REALITY_XHTTP_PATH:-}" RW_REALITY_XHTTP_SNI="${REALITY_XHTTP_SNI:-}" \
      RW_REALITY_XHTTP_PRIVATE_KEY="${REALITY_XHTTP_PRIVATE_KEY:-}" RW_REALITY_XHTTP_SHORTID="${REALITY_XHTTP_SHORTID:-}" \
      RW_ENABLE_CDN_XHTTP="$ENABLE_CDN_XHTTP" RW_CDN_XHTTP_PORT="${CDN_XHTTP_LOCAL_PORT:-}" \
      RW_CDN_XHTTP_PATH="${CDN_XHTTP_PATH:-}" RW_CDN_DOMAIN="${CDN_PUBLIC_DOMAIN:-}" \
      RW_CDN_XHTTP_CERT_PEM="${CDN_XHTTP_CERT_PEM:-}" RW_CDN_XHTTP_KEY_PEM="${CDN_XHTTP_KEY_PEM:-}" \
      RW_ENABLE_HY2="$ENABLE_HY2" RW_HY2_PORT="${HY2_PORT:-}" \
      RW_HY2_CERT_FILE="/etc/xray-certs/hy2-cert.crt" RW_HY2_KEY_FILE="/etc/xray-certs/hy2-key.pem" \
      RW_HY2_CERT_PEM="${HY2_CERT_PEM:-}" RW_HY2_KEY_PEM="${HY2_KEY_PEM:-}" \
      python3 /opt/remnanode/remnawave_provision.py || die "Автопровижининг не удался — прочитай ошибку выше"

    if [[ "${EXISTING_NODE:-false}" != true ]]; then
      echo ""
      log "Запись ноды создана в панели. Теперь нужен её SECRET_KEY."
      echo "Зайди в панель -> Ноды -> найди только что созданную ноду -> Важная информация -> скопируй ключ."
      read -rp "Вставь SECRET_KEY сюда: " SECRET_KEY
      [[ -n "$SECRET_KEY" ]] || die "SECRET_KEY обязателен для запуска контейнера ноды"
    fi
  fi

  if [[ "${EXISTING_NODE:-false}" != true ]]; then
    mkdir -p /opt/remnanode
    cd /opt/remnanode
    cat > .env <<EOF
SECRET_KEY=$SECRET_KEY
NODE_PORT=$NODE_PORT
XTLS_API_PORT=$XTLS_API_PORT
EOF
    cat > docker-compose.yml <<'EOF'
services:
  remnanode:
    container_name: remnanode
    hostname: remnanode
    image: remnawave/node:latest
    restart: always
    env_file:
      - .env
    network_mode: host
EOF
    log "Запускаю контейнер ноды..."
    docker compose up -d

    # Панель сама инициирует соединение К ноде на NODE_PORT/XTLS_API_PORT — это не мы к ней стучимся.
    EXTRA_INPUT_RULES="        tcp dport { $NODE_PORT, $XTLS_API_PORT } "
    if [[ -n "$PANEL_IP" ]]; then
      EXTRA_INPUT_RULES+="ip saddr $PANEL_IP accept"
    else
      EXTRA_INPUT_RULES+="accept"
      warn "NODE_PORT/XTLS_API_PORT открыты для любого источника — в следующий раз укажи IP панели"
    fi
  else
    EXTRA_INPUT_RULES=""
  fi

  [[ "$ENABLE_REALITY_TCP" == true ]] && EXTRA_INPUT_RULES+=$'\n'"        tcp dport $REALITY_TCP_PORT accept"
  [[ "$ENABLE_REALITY_GRPC" == true ]] && EXTRA_INPUT_RULES+=$'\n'"        tcp dport $REALITY_GRPC_PORT accept"
  [[ "$ENABLE_REALITY_XHTTP" == true ]] && EXTRA_INPUT_RULES+=$'\n'"        tcp dport $REALITY_XHTTP_PORT accept"
  [[ "$ENABLE_HY2" == true ]] && EXTRA_INPUT_RULES+=$'\n'"        udp dport $HY2_PORT accept"
  [[ "$ENABLE_CDN_XHTTP" == true && "${EXISTING_NODE:-false}" == true ]] && EXTRA_INPUT_RULES+=$'\n'"        tcp dport $CDN_XHTTP_LOCAL_PORT accept"

  if [[ "$ENABLE_CDN_XHTTP" == true && "${EXISTING_NODE:-false}" != true ]]; then
    apt install -y -qq nginx certbot
    write_nginx_hardening
    issue_cert_for_domain "$NODE_ORIGIN_DOMAIN"
    write_decoy_site

    cat > /etc/nginx/sites-available/remnanode-cdn <<EOF
upstream xray_xhttp { server 127.0.0.1:$CDN_XHTTP_LOCAL_PORT; keepalive 128; }
server {
    listen 80; server_name $NODE_ORIGIN_DOMAIN;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl; http2 on; server_name $NODE_ORIGIN_DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$NODE_ORIGIN_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$NODE_ORIGIN_DOMAIN/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    location $CDN_XHTTP_PATH {
        proxy_pass http://xray_xhttp;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_cache off;
        proxy_max_temp_file_size 0;
        proxy_socket_keepalive on;
        client_max_body_size 0;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        add_header X-Accel-Buffering no always;
        add_header Cache-Control "no-store, no-cache" always;
        add_header Accept-Ranges none always;
    }

    location / {
        root /var/www/decoy-cdn;
        index index.html;
    }
}
EOF
    ln -sf /etc/nginx/sites-available/remnanode-cdn /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default
    nginx -t && systemctl reload nginx

    EXTRA_INPUT_RULES+=$'\n'"        tcp dport { 80, 443 } accept"
  fi

  if [[ "${EXISTING_NODE:-false}" == true ]]; then
    echo ""
    warn "Firewall на этой ноде не трогаю автоматически — не знаю, что уже настроено хостером."
    echo "Открой на ней (любым способом, каким управляется её firewall) следующие порты:"
    echo "$EXTRA_INPUT_RULES" | grep -v '^$'
  else
    write_nftables_base
  fi

  if [[ "${INBOUNDS_CHOICE:-}" == "1" ]]; then
    try_fetch_inbound_templates || true
  fi

  echo ""
  echo "==================================================="
  log "Готово."
  echo "==================================================="
  if [[ "${EXISTING_NODE:-false}" != true ]]; then
    echo "NODE_PORT: $NODE_PORT   XTLS_API_PORT: $XTLS_API_PORT"
    echo ""
    echo "Проверь страницу Нод в панели — эта нода должна появиться"
    echo "подключённой в течение нескольких секунд. Если нет: docker logs remnanode"
  else
    echo "Инбаунды применены к существующей ноде ($RW_EXISTING_NODE_UUID)."
    echo "Проверь страницу Нод в панели — новые инбаунды должны появиться сразу."
  fi
  echo ""
  if [[ "$ENABLE_REALITY_TCP" == true ]]; then
    echo "--- Reality+TCP ---"
    echo "  port: $REALITY_TCP_PORT  sni: $REALITY_TCP_SNI  pbk: $REALITY_TCP_PUBLIC_KEY  sid: $REALITY_TCP_SHORTID"
  fi
  if [[ "$ENABLE_REALITY_GRPC" == true ]]; then
    echo "--- Reality+gRPC ---"
    echo "  port: $REALITY_GRPC_PORT  sni: $REALITY_GRPC_SNI  pbk: $REALITY_GRPC_PUBLIC_KEY  sid: $REALITY_GRPC_SHORTID  serviceName: $REALITY_GRPC_SERVICE_NAME"
  fi
  if [[ "$ENABLE_REALITY_XHTTP" == true ]]; then
    echo "--- Reality+XHTTP (прямое подключение, без CDN) ---"
    echo "  port: $REALITY_XHTTP_PORT  sni: $REALITY_XHTTP_SNI  pbk: $REALITY_XHTTP_PUBLIC_KEY  sid: $REALITY_XHTTP_SHORTID  path: $REALITY_XHTTP_PATH"
  fi
  if [[ "$ENABLE_HY2" == true ]]; then
    echo "--- Hysteria2 ---"
    echo "  port: $HY2_PORT (самоподписанный сертификат — в клиенте нужен pinSHA256 или insecure=1)"
  fi
  if [[ "$ENABLE_CDN_XHTTP" == true ]]; then
    echo "--- TLS+XHTTP через CDN ---"
    echo "  https://$CDN_PUBLIC_DOMAIN$CDN_XHTTP_PATH (origin: https://$NODE_ORIGIN_DOMAIN$CDN_XHTTP_PATH)"
    echo "  Host в панели создан автоматически (см. вывод провижининга выше)."
    if [[ "${EXISTING_NODE:-false}" == true ]]; then
      echo "  В консоли CDN-провайдера для этого ресурса укажи:"
      echo "    Протокол для источников: HTTPS"
      echo "    Порт источника: $CDN_XHTTP_LOCAL_PORT (не 443 по умолчанию — свободен на этой ноде)"
      echo "  Сертификат на origin — самоподписанный (сгенерирован этим скриптом)."
      echo "  Если CDN откажется его принимать — замени /etc/xray-certs/hy2-cert.crt"
      echo "  и /etc/xray-certs/hy2-key.pem на настоящий (например, из Yandex Certificate"
      echo "  Manager) до запуска этого шага, либо перезапусти провижининг заново."
    fi
  fi
  echo "==================================================="
}

#################################
# DISPATCH
#################################
case "$MODE" in
  panel) install_panel ;;
  node) install_node ;;
esac
